package:
  name: classiflib
  version: 1.1.0
source:
  git_url: ../

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

  # Specify additional env vars pass through
  # script_env:
  #   - ENV_VAR_HERE

requirements:
  build:
    - python {{ python }}
    - numpy
    - h5py
    - scikit-learn
    - setuptools
    - traits

  run:
    - python {{ python }}
    - numpy
    - h5py
    - scikit-learn
    - traits
    # - vs2015_runtime  [win]

test:
  # Test that we can import the package
  imports:
    - classiflib

about:
  home: https://github.com/pennmem/classiflib
  summary: Classifier serialization library
  # license: FIXME
  # license_file: FIXME
